"""P4 dry run: simulation-based parameter recovery / identifiability for the calibration design.

Question answered (NO human data, NO model/LM run -- pure numpy on the cached gate output): if the
human edit-rates were generated by the model at KNOWN dial settings, can the planned fit recover
those settings, and which dials trade off? This is the go/no-go check before scaling the battery or
touching real data (planning/CALIBRATION_PLAN.md P4).

Reduction (the 2-reading model: literal vs edited). For item i the model's edit-probability is
logistic in the free parameters:

    logit q_i = lambda * g_i  +  channel_i(theta)

  g_i              = the LM's preference for the correction (cached `slp_gain`; for a matched
                     plausible/keep item, the would-be edit's preference `contrast_gain_keep`).
  channel_i        = WDEL                         (deletion items: missing-word cost)
                   = log(rho_ins) - surp_uni(w)   (insertion items: spurious-word cost; surp known)
                   = kappa_sub * d_i              (substitution items: per-char-edit cost x distance)

So logit q_i = X_i . theta + offset_i with theta = (lambda, WDEL, log_rho_ins, kappa_sub) and design
columns X_i = [g_i, 1{del}, 1{ins}, d_i*1{sub}], offset_i = -surp_uni for insertions. That is a
binomial GLM; the Fisher information X^T W X gives the parameter covariance -> SDs + the trade-off
(correlation) structure directly. Recovery is checked by simulating counts at theta_star and refitting.

Run:  conda run -n ncgenjax python -u -m genjax_port.calibration_identifiability
"""
import csv
import sys

import numpy as np

GATED = "planning/calibration_battery_v0_gated.csv"

# Truth used to generate synthetic data (sensible, places items across the decision boundary).
THETA_STAR = dict(lam=1.0, wdel=-3.0, log_rho_ins=-3.0, kappa_sub=-5.45)
PNAMES = ["lambda", "WDEL", "log_rho_ins", "kappa_sub"]
N_PER_ITEM = 40      # synthetic participants per item
N_SIMS = 400         # repeated synthetic datasets for recovery stats
SEED = 0


def _surp_uni(word):
    """Out-of-context unigram surprisal (nats) of a word; wordfreq if available, else a fallback."""
    try:
        import wordfreq
        p = wordfreq.word_frequency(word.lower(), "en")
        return float(-np.log(p)) if p > 0 else 12.0
    except Exception:
        return {"handed": 11.5, "on": 6.9, "quickly": 9.8}.get(word.lower(), 10.0)


def load_items(path):
    rows = list(csv.DictReader(open(path)))
    pair_d = {}        # pair_id -> edit_distance of its edit member (for keep-item lookup)
    pair_spur = {}     # pair_id -> spurious word (INS edit member) for keep-item surprisal
    for r in rows:
        if r["expected"] == "edit" and r["edit_distance"]:
            pair_d[r["pair_id"]] = int(r["edit_distance"])
        if r["expected"] == "edit" and r["edit_type"] == "ins" and r["edit_from"]:
            pair_spur[r["pair_id"]] = r["edit_from"]
    items = []
    for r in rows:
        et = r["edit_type"]
        if r["expected"] == "edit" and r["gate_pass"] == "PASS":
            g = float(r["slp_gain"])
            if et == "sub":
                kind, d, surp = "sub", int(r["edit_distance"]), 0.0
            elif et.startswith("del"):
                kind, d, surp = "del", 0, 0.0
            elif et == "ins":
                kind, d, surp = "ins", 0, _surp_uni(r["edit_from"])
            else:
                continue
            items.append(dict(id=r["item_id"], kind=kind, g=g, d=d, surp=surp))
        elif r["expected"] == "keep" and r["contrast_gain_keep"]:
            # matched plausible context: the would-be edit should be REJECTED (negative-preference anchor)
            g = float(r["contrast_gain_keep"])
            if r["family"].startswith("SUB"):
                items.append(dict(id=r["item_id"], kind="sub", g=g, d=pair_d.get(r["pair_id"], 1), surp=0.0))
            elif r["family"].startswith("INS"):
                items.append(dict(id=r["item_id"], kind="ins", g=g, d=0,
                                  surp=_surp_uni(pair_spur.get(r["pair_id"], ""))))
    return items


def design(items):
    X = np.zeros((len(items), 4))
    off = np.zeros(len(items))
    for i, it in enumerate(items):
        X[i, 0] = it["g"]                          # lambda
        if it["kind"] == "del":
            X[i, 1] = 1.0                           # WDEL
        elif it["kind"] == "ins":
            X[i, 2] = 1.0                           # log_rho_ins
            off[i] = -it["surp"]
        elif it["kind"] == "sub":
            X[i, 3] = it["d"]                        # kappa_sub
    return X, off


def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-np.clip(z, -30, 30)))


# Weak Gaussian prior precision on theta (the plan's weakly-informative prior). Regularizes the fit,
# prevents divergence when a few items perfectly separate (e.g. only 3 insertion items) -> MAP, not MLE.
PRIOR_PREC = 0.01


def nll(theta, X, off, k, N):
    q = sigmoid(X @ theta + off)
    q = np.clip(q, 1e-12, 1 - 1e-12)
    return -(k * np.log(q) + (N - k) * np.log(1 - q)).sum() + 0.5 * PRIOR_PREC * (theta @ theta)


def cov_at(theta, X, off, N):
    """Posterior covariance = (Fisher info + prior precision)^-1 at theta."""
    W = N * sigmoid(X @ theta + off) * (1 - sigmoid(X @ theta + off))
    info = X.T @ (X * W[:, None]) + PRIOR_PREC * np.eye(X.shape[1])
    return np.linalg.inv(info)


def irls(X, off, k, N, iters=100):
    """MAP fit (logit eta = X@theta + off) via damped IRLS with backtracking. Returns theta, cov."""
    theta = np.zeros(X.shape[1])
    for _ in range(iters):
        q = sigmoid(X @ theta + off)
        grad = X.T @ (k - N * q) - PRIOR_PREC * theta
        W = N * q * (1 - q)
        H = X.T @ (X * W[:, None]) + PRIOR_PREC * np.eye(X.shape[1])
        step = np.linalg.solve(H, grad)
        f0 = nll(theta, X, off, k, N)
        t = 1.0                                   # backtracking line search
        while t > 1e-6 and nll(theta + t * step, X, off, k, N) > f0:
            t *= 0.5
        theta = theta + t * step
        if np.max(np.abs(t * step)) < 1e-9:
            break
    return theta, cov_at(theta, X, off, N)


def main():
    items = load_items(GATED)
    X, off = design(items)
    theta_star = np.array([THETA_STAR[n] for n in ["lam", "wdel", "log_rho_ins", "kappa_sub"]])
    q_star = sigmoid(X @ theta_star + off)
    counts_per_param = (X != 0).sum(axis=0)

    print("================ P4 IDENTIFIABILITY DRY RUN ================")
    print(f"items: {len(items)}  (N={N_PER_ITEM}/item, {N_SIMS} synthetic datasets)")
    print(f"items informing each dial: " +
          ", ".join(f"{PNAMES[j]}={int(counts_per_param[j])}" for j in range(4)))
    print(f"design rank: {np.linalg.matrix_rank(X)}/4  (4 = all dials separately identified)")

    # (1) asymptotic covariance at the truth (Fisher information at theta_star; no fitting) -> trade-offs.
    cov0 = cov_at(theta_star, X, off, N_PER_ITEM)
    sd0 = np.sqrt(np.diag(cov0))
    corr = cov0 / np.outer(sd0, sd0)
    print("\n-- asymptotic 1-sigma width of each dial (smaller = better pinned) --")
    for j, n in enumerate(PNAMES):
        print(f"   {n:12s} true={theta_star[j]:+7.3f}   sd={sd0[j]:.3f}")
    print("\n-- dial-to-dial correlation (trade-offs; |r|->1 means confounded) --")
    print("              " + "".join(f"{n[:9]:>11s}" for n in PNAMES))
    for j, n in enumerate(PNAMES):
        print(f"   {n:11s} " + "".join(f"{corr[j,l]:>11.2f}" for l in range(4)))

    # (2) repeated recovery: simulate counts at theta_star, refit, collect.
    rng = np.random.default_rng(SEED)
    hats = np.zeros((N_SIMS, 4))
    sds = np.zeros((N_SIMS, 4))
    for s in range(N_SIMS):
        k = rng.binomial(N_PER_ITEM, q_star)
        th, cv = irls(X, off, k.astype(float), N_PER_ITEM)
        hats[s] = th
        sds[s] = np.sqrt(np.diag(cv))
    bias = hats.mean(0) - theta_star
    rmse = np.sqrt(((hats - theta_star) ** 2).mean(0))
    cover = (np.abs(hats - theta_star) < sds).mean(0)   # 1-sigma coverage (~0.68 if calibrated)
    print("\n-- recovery over", N_SIMS, "synthetic datasets --")
    print(f"   {'dial':12s} {'true':>8s} {'mean_hat':>9s} {'bias':>8s} {'rmse':>7s} {'1sig_cov':>9s}")
    for j, n in enumerate(PNAMES):
        print(f"   {n:12s} {theta_star[j]:>8.3f} {hats[:,j].mean():>9.3f} "
              f"{bias[j]:>+8.3f} {rmse[j]:>7.3f} {cover[j]:>9.2f}")

    # (3) verdict
    print("\n-- read --")
    weak = [PNAMES[j] for j in range(4) if counts_per_param[j] < 5]
    confounded = [(PNAMES[a], PNAMES[b]) for a in range(4) for b in range(a + 1, 4)
                  if abs(corr[a, b]) > 0.7]
    print(f"   well-recovered (bias~0, tight): "
          f"{[PNAMES[j] for j in range(4) if abs(bias[j])<0.15 and rmse[j]<max(0.5,abs(theta_star[j])*0.5)]}")
    print(f"   under-powered (few items, wide): {weak or 'none'}")
    print(f"   notable trade-offs (|r|>0.7): {confounded or 'none'}")
    print("===========================================================")


if __name__ == "__main__":
    main()
